### ISSUE TITLE
Indirect exception when setting maracluster pval threshold

### ISSUE THREAD

**Issue by chrashwood** [statisticalbiotechnology/quandenser#15]
When trying to set the maracluster pvalue threshold, there is an exception for the -t option which was not specified in the run parameters. This appears to be specific for the maracluster pval threshold.
```
C:\Users\chras\mzML Files> quandenser -b "file_list.txt" --max-missing 3 --dinosaur-memory 16G --maracluster-pval-threshold -30.0
Exception caught: -t option requires a float between -1000 and 0
```
Trying to manually set -t to 0.2 does not fix this.

```
C:\Users\chras\mzML Files> quandenser -b "file_list.txt" --max-missing 3 --dinosaur-memory 16G --percolator-test-fdr 0.02 --maracluster-pval-threshold -30.0
Exception caught: -t option requires a float between -1000 and 0
```

Cheers,
Chris

**Comment by MatthewThe** [comment]
Apparently, I made a dumb copy-paste error... I fixed it now. If you want, I could build a binary installer for you to test.

**Comment by chrashwood** [comment]
Yes please! Thank you.

**Comment by MatthewThe** [comment]
There you go (I assumed you were working on windows 64-bit): [quandenser-v0-02-win64-msvc-x64.zip](https://github.com/statisticalbiotechnology/quandenser/files/4086482/quandenser-v0-02-win64-msvc-x64.zip)

**Comment by chrashwood** [comment]
Thanks. Good assumption.
