### ISSUE TITLE
quickbuild.sh failing with missing file

### ISSUE THREAD

**Issue by ijmiller2** [statisticalbiotechnology/quandenser#3]
Last line of the error message is:

```bash
cp: cannot stat '/home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/quandenser/quan*.deb': No such file or directory
```

Running on Ubuntu 18.04.2 LTS. I've attached the full output from .stdout.

Let me know if you need any other details to help troubleshoot. 

Also, have you considered building a Docker image for quandenser?

Thanks in advance for your support,
Ian
[quickbuild.stdout.txt](https://github.com/statisticalbiotechnology/quandenser/files/3233091/quickbuild.stdout.txt)

**Comment by percolator** [comment]
Hi Ian,

Sorry to hear you have difficulties with the building process.

Here is where your build fails:
======
Checking packages:
CMake Error at /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:106
(find_package):
  Found package configuration file:

/usr/local/lib/cmake/boost_filesystem-1.71.0/boost_filesystem-config.cmake
  but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem"
is
  considered to be NOT FOUND.  Reason given by package:
  No suitable build variant has been found.
  The following variants have been tried and rejected:
  * libboost_filesystem.so.1.71.0 (shared, Boost_USE_STATIC_LIBS=ON)
  * libboost_filesystem.a (shared runtime, Boost_USE_STATIC_RUNTIME=ON)
======
I think you should just get the right versions of the boost libraries.

And yes we are trying to make a (singularity) container out of quandenser:
https://github.com/statisticalbiotechnology/quandenser-pipeline

**Comment by ijmiller2** [comment]
Hi Lukas,

Okay, thanks for the info. I suspected it might be originating from a boost version issue too based on that message. I can try a different/earlier version. Which version are you using?

Thanks,
Ian

**Comment by MatthewThe** [comment]
Hi Ian,

We use version 1.67.0, but this dependency should be fulfilled through the ProteoWizard build. Can you check if ProteoWizard built correctly by looking for the static libraries named "libboost_..." and "libpwiz_..." in the "~/build/ubuntu64/tools/lib" directory?

**Comment by ijmiller2** [comment]
Hey Matthew,

Thanks for the info. I assume you mean to represent my home directory path with "~"? If so, I'm not seeing any directory called "build" there. Or within the quandenser directory for that matter (since that's where I'm running `sudo ./quickinstall.sh` after cloning recursively as specified: `git clone --recursive https://github.com/statisticalbiotechnology/quandenser.git`.

Let me know if there's any other info I can provide.

Thanks for the help,
Ian

**Comment by MatthewThe** [comment]
Hi Ian,

Sorry, I only realized now you're building from a different directory than the home directory. The folder you should check is /home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/tools/lib.

**Comment by ijmiller2** [comment]
Hey Matthew,

Yes, I do see some relevant looking files/directories in that directory (~/Desktop/For_Gary/build/ubuntu64/tools/lib):

libpwiz_analysis_chromatogram_processing.a
libpwiz_analysis_common.a
libpwiz_analysis_demux.a
libpwiz_analysis_frequency.a
libpwiz_analysis_passive.a
libpwiz_analysis_passive_core.a
libpwiz_analysis_peakdetect.a
libpwiz_analysis_peptideid.a
libpwiz_analysis_proteome_processing.a
libpwiz_analysis_spectrum_processing.a
libpwiz_analysis_spectrum_processing_basic.a
libpwiz_analysis_version.a
libpwiz_data_common.a
libpwiz_data_identdata.a
libpwiz_data_identdata_examples.a
libpwiz_data_identdata_version.a
libpwiz_data_misc.a
libpwiz_data_msdata.a
libpwiz_data_msdata_examples.a
libpwiz_data_msdata_version.a
libpwiz_data_obo.a
libpwiz_data_proteome.a
libpwiz_data_proteome_examples.a
libpwiz_data_proteome_version.a
libpwiz_data_vendor_readers.a
libpwiz_reader_abi.a
libpwiz_reader_abi_t2d.a
libpwiz_reader_agilent.a
libpwiz_reader_bruker.a
libpwiz_reader_shimadzu.a
libpwiz_reader_thermo.a
libpwiz_reader_uimf.a
libpwiz_reader_unifi.a
libpwiz_reader_waters.a
libpwiz_utility_chemistry.a
libpwiz_utility_image.a
libpwiz_utility_math.a
libpwiz_utility_minimxml.a
libpwiz_utility_misc.a
libpwiz_version.a
...
libboost_chrono.a
libboost_chrono-gcc7-mt-s.a
libboost_date_time-gcc7-mt-s.a
libboost_filesystem.a
libboost_filesystem-gcc7-mt-s.a
libboost_iostreams.a
libboost_iostreams-gcc7-mt-s.a
libboost_nowide-gcc7-mt-s.a
libboost_program_options.a
libboost_program_options-gcc7-mt-s.a
libboost_regex.a
libboost_regex-gcc7-mt-s.a
libboost_serialization.a
libboost_serialization-gcc7-mt-s.a
libboost_system.a
libboost_system-gcc7-mt-s.a
libboost_thread.a
libboost_thread-gcc7-mt-s.a

Anything obvious missing?

I'll attach more info on the directory and file metadata for your reference.

Thanks for the help,
Ian

[build_ubuntu64_tools_lib_dir_contents.txt](https://github.com/statisticalbiotechnology/quandenser/files/3263627/build_ubuntu64_tools_lib_dir_contents.txt)

**Comment by MatthewThe** [comment]
Thanks, that actually looks as it is supposed to. 

It seems CMake is picking up on another local boost build. I'm not sure why it does not give preference to the CMAKE_PREFIX_PATH that we are setting, but you can try adding `-DBoost_NO_BOOST_CMAKE=BOOL:ON` to the cmake command in the build file (you might also need to remove the folder `/home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/quandenser` to ensure it does not use cached values).

**Comment by ijmiller2** [comment]
I'm not familiar enough with `cmake` to know which file and line to modify with `DBoost_NO_BOOST_CMAKE=BOOL:ON`. Are you referring to the `quick build.sh` as the "build file"? I don't see any explicit cmake commands in that file. Or do you mean one of the .cmake files in quandenser/cmake directory? I see currently see four: 

FindProteoWizard.cmake
FindPthreads.cmake
MacroFindPackage.cmake
VersionGen.cmake

**Comment by ijmiller2** [comment]
I think I found that build file: 

`/home/ijmiller2/Desktop/For_Gary/quandenser/admin/builders/ubuntu64_build.sh` and the cmake command in it, which I updated with that flag (after removing the `/home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/quandenser` as suggested):
`cmake -DTARGET_ARCH=amd64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DBOOST_VARIANT_DO_NOT_USE_VARIADIC_TEMPLATES=ON -DCMAKE_PREFIX_PATH=$build_dir/tools $src_dir/quandenser -DBoost_NO_BOOST_CMAKE=BOOL:ON;`

Unfortunately, still getting an error (attached). Though looks like it may be for a different reason? This one for building Dinosaur "Cannot create module Dinosaur, mvn execution failed: 1"

[7-Jun-19_quickbuild.stdout.txt](https://github.com/statisticalbiotechnology/quandenser/files/3267393/7-Jun-19_quickbuild.stdout.txt)

**Comment by MatthewThe** [comment]
Yes, that was indeed where you should add the flag. The error you get now indicates a problem with Java or Maven, which both should have been installed by the build script.

Could you post the contents of the files:
/home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/quandenser/dinosaur_maven_stdout.txt
/home/ijmiller2/Desktop/For_Gary/quandenser/../build/ubuntu64/quandenser/dinosaur_maven_stderr.txt

One problem I've encountered before is a too new version of Java JDK. The dinosaur build works with JDK 8, but not with JDK 11.

**Comment by ijmiller2** [comment]
Here are those two files. Looks like it could be something Java version related, as you suggested.

[dinosaur_maven_stderr.txt](https://github.com/statisticalbiotechnology/quandenser/files/3270103/dinosaur_maven_stderr.txt)
[dinosaur_maven_stdout.txt](https://github.com/statisticalbiotechnology/quandenser/files/3270104/dinosaur_maven_stdout.txt)

**Comment by MatthewThe** [comment]
Yes, that indeed seems to be a Java version error. Could you try to (temporarily) change to JDK 8 with `sudo update-alternatives --config java` and following the instructions?

**Comment by ijmiller2** [comment]
The switch to JDK 8 seemed to resolve it. We've got everything compiled and running now. 

Thanks for your support!
Ian
