### ISSUE TITLE
m/z calibration and aligning between separate experiments

### ISSUE THREAD

**Issue by andrewjmc** [statisticalbiotechnology/quandenser#5]
Hello,

I am really excited by this tool, which seems to do everything I would want for our discovery metaproteomics experiment. Our data has been acquired in three batches - two in the same lab and instrument (but with MS2 switched between FTMS and ITMS) and one in another lab on a different instrument (Orbitrap). The LCMS conditions will be different (details not to hand).

I have two questions, if you have a chance to give your thoughts.

**Question 1**
Even if I initially analyse the two laboratories separately, it would be most useful if I could further assign a correspondence between the labs, at both spectral and feature level.

This shows the correspondence between MaxQuant's calibrated retention times (per batch) for each peptide species in the two labs (where there are multiple peptide IDs, I have made it an intensity-weighted mean):

![image](https://user-images.githubusercontent.com/11620733/69140042-9f88ed80-0ab9-11ea-85ef-aca11012d77b.png)

Is it worth trying all files together and seeing how well the chromatograms can be aligned? Or can you suggest a better approach?

**Question 2**
MaxQuant does an initial search which allows it to calibrate m/z values dependent upon m/z and retention time. I anticipate the improvement in mass accuracy and precision, would assist in matching features between runs. With my data, (using one lab as an example), per sample uncalibrated mass errors are from -3.1 to -0.5 ppm (5th percentile) to +1 to +2 ppm (95th percentile). After calibration, this becomes -1.8 to -0.8 ppm (5th percentile) to +0.9 to 1.7 ppm (95th percentile).

If it were possible to extract the calibration functions from the MaxQuant output, would it be feasible (and beneficial) to apply these within Quandenser?

Thanks for your advice,

Andrew

**Comment by MatthewThe** [comment]
Hi Andrew, 

Great to hear that you are interested in using Quandenser!

Q1: Based on your plot, I think it's worth a try to simply align the retention times of the different labs inside Quandenser.

Q2: I don't expect a huge benefit from the mass calibration, unless there is a clear bias to either direction, which does not seem to be the case. Using the calibration functions from MaxQuant is likely quite tricky unless it's a simple (linear) transformation, though if you manage to extract such a transformation from MaxQuant I'll be happy to take a look at it.

**Comment by andrewjmc** [comment]
Really helpful, thanks. I'll give it a go and get back to you if I have a correction formula and think it's worth giving it a go.

Best wishes,

Andrew
