### ISSUE TITLE
Maracluster mz tolerance

### ISSUE THREAD

**Issue by andrewjmc** [statisticalbiotechnology/quandenser#6]
Can I just check that the Maracluster mz tolerance parameter determines the tolerance of the precursor mass within a cluster, and not the tolerance of fragment masses? I saw in a separate issue on Maracluster that it uses a 1 Da fragment mass tolerance (https://github.com/statisticalbiotechnology/maracluster/issues/10). Is that still the case?

Thanks,

Andrew

**Comment by MatthewThe** [comment]
Yes, that is correct.

**Comment by andrewjmc** [comment]
Great, thanks.

Andrew
